### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: mire_explain_enhance2_img,mire_explain_enhance2_dia,mire_explain_enhance2_mask_img,mire_explain_enhance2_mask_dia,mire_explain_enhance2_noise_img,mire_explain_enhance2_noise_dia
template: qwen2_vl
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/qwen2_vl-7b/full/sft-ep3
logging_steps: 10
save_steps: 0
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

report_to: wandb
run_name: wrj_qwenvl # optional