### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64
lora_alpha: 32
lora_dropout: 0.05
resume_from_checkpoint: false

### dataset
# dataset: mllm_demo,identity,alpaca_en_demo  # video: mllm_video_demo
# template: qwen2_vl
# cutoff_len: 2048
# max_samples: 1000
# overwrite_cache: true
# preprocessing_num_workers: 16

dataset: mire_train  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 4096
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/qwen2_vl-7b/lora/sft-v1
logging_steps: 10
save_steps: 0.25
plot_loss: true
overwrite_output_dir: true

# logging_steps: 1
# save_steps: 0.2
# plot_loss: true
# overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 0.1

# flash_attn: fa2
deepspeed: examples/deepspeed/ds_z2_config.json
